### PR TITLE
[Userinfo] Fix Adventure bank stats

### LINKED ISSUE #153: [userinfo] Fails when Economy and Adventure is loaded
**Describe the bug**
Command fails when Economy and Adventure is loaded:

```python
Exception in command 'userinfo'
Traceback (most recent call last):
  File "/Users/michael/Development/clasko-cogs/.venv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/Users/michael/Library/Application Support/Red-DiscordBot/data/Jarvis/cogs/CogManager/cogs/userinfo/userinfo.py", line 350, in userinfo
    adventure_currency = await adventure_bank.get_balance(user)
AttributeError: module 'adventure.bank' has no attribute 'get_balance'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/clasko/Development/clasko-cogs/.venv/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/Users/clasko/Development/clasko-cogs/.venv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/Users/clasko/Development/clasko-cogs/.venv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: module 'adventure.bank' has no attribute 'get_balance'
```

Cog Version is 0.3.1

## System Metadata:
CPU Cores: 10 (arm64)
RAM: 6.9GB/16.0GB (68.0%)

## OS Variables:
OS version: Mac OSX 12.2 arm64
User: clasko
Python executable: /Users/clasko/Development/clasko-cogs/.venv/bin/python
Python version: 3.9.7 (64bit)
Pip version: 22.0.3
Red version: 3.4.16
Discord.py version: 1.7.3

## Red variables:
Instance name: Jarvis
Owner(s): 183628039245004800 (Clasko#1337)
Storage type: JSON
Disabled intents: None
Data path: /Users/clasko/Library/Application Support/Red-DiscordBot/data/Jarvis
Metadata file: /Users/clasko/Library/Application Support/Red-DiscordBot/config.json

### PR DESCRIPTION
**Pull request by Clasko**
Fixes #153

I'm not sure if this is the best way to fix it but it works for me.

### CODE REVIEW

**Comment by flaree** [comment]
This changes nothing with regards to the error in that issue.

**Comment by flaree** [comment]
The error is about the attribute not existing, this does not fix that.

**Comment by flaree** [comment]
The current fix is to reload userinfo, that will fix the error as of now

**Comment by Clasko** [comment]
Cog reload does not work for me:
grafik

**Pull request closed without merging**
