### PR TITLE
Cleanup unbelieveaboat default replies

### PR DESCRIPTION
**Pull request by leetfin**
Remove some duplicate responses, spellcheck, clean up multiple spaces. Used gender-neutral language where possible.

### CODE REVIEW

**Comment by flaree** [comment]
Not sure if you meant this mark this as a draft or not?

**Comment by leetfin** [comment]
I did, there's still some duplicates I didn't get to.

**Comment by leetfin** [comment]
@flaree If you could please review this for hacktoberfest that would be awesome ^ ^

**Comment by leetfin** [comment]
Thank you so much!

**Pull request merged**
