### PR TITLE
Update f1.py - race_notification_check func added

### PR DESCRIPTION
**Pull request by JohnBeres**
Original code didn't have a function to check whether or not it was a race day. This was something quickly generated by GPT-4 LLM. Please note: `await asyncio.sleep(60)` on line 482 has this action performing every minute. Adjust as needed.

Feel free to edit as needed, just figured folks would appreciate this working!

### CODE REVIEW

**Comment by flaree** [comment]
There's already code to support sending a notif for race day, I dont see the point in spamming a reminder every hour.

Also, I will not blindly accept any AI generated code. Specifically when it doesn't know Red and it's inner workings.

**Comment by JohnBeres** [comment]
Yea async def raceday_loop(self):. I'll close. But an interesting point, your function was never being called. Adjusted as shown and the raceday posts are occuring as intended.

**Comment by flaree** [comment]
its called every day at midnight UTC

 - https://github.com/flaree/flare-cogs/blob/master/f1/f1.py#L34
 - https://github.com/flaree/flare-cogs/blob/master/f1/f1.py#L47

**Comment by JohnBeres** [comment]
I was on the master branch, I'll switch over to dpy2 and use the original code to test. Thank-you!

**Pull request closed without merging**
